### PR TITLE
Provide aemm error instead of cordova error

### LINKED ISSUE #29: Running build command without a platform instructs user to use cordova
When running `aemm build <platform>` with no platforms installed, the error message reads 
```
Error: No platforms added to this project. Please use `cordova platform add <platform>`.
```

It should instruct the user to use an `aemm` command instead.

### PR DESCRIPTION
**Pull request by adzellman**
- Fixes #29
 - When build is requested but no platforms added, intercept the error and
   provide an aemm-specific error instead of a cordova-specific error.

@EonerAemm

### CODE REVIEW

File: src/build.js [hunk 1]
```diff
@@ -25,6 +25,13 @@ function build(args, platform)
     return Q.fcall( () => {
         var platformBuildModule = platformRequire("build", platform);
         return platformBuildModule.build(args);
+    }).catch( (err) => {
+        if (err.message == "No platforms added to this project. Please use `cordova platform add <platform>`.") {
```
Comment (HenryPing) [inline src/build.js]: Can we use the err.code instead? for faster check

Comment (adzellman) [inline src/build.js]: Cordova is passing us Code 0, which I doubt we can depend on to mean this exact error.

**Comment by adzellman** [comment]
Low impact, going ahead with this merge.
